name: Dockerized greetings
description: Greet the user from Docker

inputs:
  greeting:
    description: Greeting to give
    required: true

runs:
  # For more on Docker actions, see:
  # https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-docker-container-action
  using: docker
  # 'docker://image:tag' uses pre-built image, 'Dockerfile' builds locally
  image: 'docker://alpine:3.20'
  entrypoint: 'sh'
  args:
    - -c
    - echo "${{ inputs.greeting }}"
  

