name: demo-workflow

on:
  workflow_dispatch:
    inputs:
      greeting:
        description: Message to show
        default: Hello!
      printEnv:
        description: Choose to print the environment
        type: boolean
        default: false

env:
  FOO: bar

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: echo ${{ inputs.greeting }}
      - name: step1
        run: uname -a
      - name: Print environment
        run: echo ${{ toJSON(env) }}
        if: inputs.printEnv == true
