name: demo-workflow

on:
  workflow_dispatch:
    inputs:
      greeting:
        description: Message to show
        required: true
        default: Hello!

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: echo ${{ inputs.greeting }}
      - name: step1
        run: uname -a
      - name: Print environment
        run: echo ${{ toJSON(env) }}
